### ISSUE TITLE
Some modifications

### ISSUE THREAD

**Issue by T-solidus-T** [yurtemre7/mouse-battery#4]
Hi,

First of all, thank you so much for developing this app, I have been looking for something like this for a few months and finally someone has developed this, it's fantastic, congrats!

I have modified a bit your script just yo adapt to my need, and I would like to share it so you can take a look. Maybe you want to add some of the changes that I have implemented in your script:
- Icon battery color changed, depending on the battery level (green, yellow or red)
- Function added to refresh battery value when you click on the third option of the icon menu. This is useful for me because sometimes the script gets a wrong battery value (less than the actual battery level), so with this function I can refresh the icon on demand.

I have uploaded the script modified to this post because I don't have to much knowledge about git, branches and so on.

Thank you again for this great application

[mouse_script.zip](https://github.com/yurtemre7/mouse-battery/files/14521914/mouse_script.zip)

**Comment by yurtemre7** [comment]
Hey, thank you for your addition to this project. I will take a good look at it later and hopefully merge your solutions in! 
Big thanks.

**Comment by yurtemre7** [comment]
Merged @T-solidus-T, release available here → [v1.0.3](https://github.com/yurtemre7/mouse-battery/releases/tag/v1.0.3)
