### ISSUE TITLE
SteelSeries Prime Mini Wireless

### ISSUE THREAD

**Issue by stychu** [yurtemre7/mouse-battery#5]
I just bought SteelSeries Prime Mini Wireless and wanted to have battery percentage insight. Unfortunately this one doesnt seem to work for Prime Mini Wireless. I see always N/A

**Comment by yurtemre7** [comment]
Hey, according to the [docs](https://flozz.github.io/rivalcfg/devices/prime_wireless.html), your mouse should be supported. Nevertheless, do you want to debug the issue yourself? Otherwise, I can help you with the process, here is my discord tag: `elarbeitslos.`

**Comment by yurtemre7** [comment]
Else, try to remove your dongle from your PC and reconnect it, as stated [here](https://github.com/yurtemre7/mouse-battery/blob/main/knownissues.md).

**Comment by yurtemre7** [comment]
Ah, wait! The package that I was using just recently added support for your mouse, I update the package in a moment, please try it with the new version in a bit!

**Comment by stychu** [comment]
> Ah, wait! The package that I was using just recently added support for your mouse, I update the package in a moment, please try it with the new version in a bit!

Sweet! I will try ;)

**Comment by stychu** [comment]
It works now ! Thank you very much <3
