### ISSUE TITLE
Aerox 5 Wireless tested correct

### ISSUE THREAD

**Issue by Fortiori** [yurtemre7/mouse-battery#9]
As in title, works well.
![Screenshot 2024-07-13 164324](https://github.com/user-attachments/assets/64a20806-7deb-420f-bf72-dd46274e7681)

Thanks for making this, would have like to have the feature in SS GG in the first place.

Also some ideas for future improvements:
- Ability to change colour of icon (even if manually)
- Option to display % as a number instead of a battery icon

**Comment by yurtemre7** [comment]
No problem!
Do you think I should try to write to Steel Series and provide my solution to them?! 

Thank you for your suggestions, I'll take a look at them, maybe even later today!

**Comment by Fortiori** [comment]
You could, I'm not how likely they are to implement - their software is a little underwhelming to me but I like it compared to Corsair and Razer because you can disable the parts you don't like.

It would also be good to implement it into one of their apps for use on their devices that have OLED screens - e.g. see mouse battery on the OLED along with headset battery.
